/**
 * NOTE (to revisit before real customers use this):
 * On re-provisioning an EXISTING device_code, this function reassigns owner_id
 * and rotates device_api_key unconditionally — any authenticated user who knows
 * or guesses a device_code can currently take ownership away from whoever
 * registered it first. Fine for internal/prototype testing since we control who
 * has access, but needs an ownership guard (e.g. reject reassignment unless
 * existing.owner_id is null or matches the caller) before shipping to customers
 * with their own accounts.
 *
 * Also: device_code is currently a random string generated by the ESP32 itself.
 * Should switch to the ESP32's MAC address instead, for physical traceability
 * (printable on a label at assembly) once we're producing multiple units.
 */
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ??
      Deno.env.get("SERVICE_ROLE_KEY")!;

    // Client using the CALLER's token, used only to verify who's calling
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: "Missing Authorization header" }),
        {
          status: 401,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        },
      );
    }

    const userClient = createClient(supabaseUrl, serviceRoleKey, {
      global: { headers: { Authorization: authHeader } },
    });

    const {
      data: { user },
      error: userError,
    } = await userClient.auth.getUser();

    if (userError || !user) {
      return new Response(
        JSON.stringify({ error: "Invalid or expired session" }),
        {
          status: 401,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        },
      );
    }

    // Admin clientto get full privileges, bypasses RLS, used for the actual write
    const adminClient = createClient(supabaseUrl, serviceRoleKey);

    const { device_code } = await req.json();

    if (!device_code || typeof device_code !== "string") {
      return new Response(
        JSON.stringify({ error: "device_code is required" }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        },
      );
    }

    // Check if this device already exists (re-provisioning case)
    const { data: existing, error: fetchError } = await adminClient
      .from("devices")
      .select("id, owner_id")
      .eq("device_code", device_code)
      .maybeSingle();

    if (fetchError) {
      return new Response(JSON.stringify({ error: fetchError.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    let deviceRow;

    if (existing) {
      // Device already known and needs reassignment
      // Reassign owner, rotate the API key
      const { data, error } = await adminClient
        .from("devices")
        .update({
          owner_id: user.id,
          device_api_key: crypto.randomUUID(),
        })
        .eq("id", existing.id)
        .select()
        .single();

      if (error) {
        return new Response(JSON.stringify({ error: error.message }), {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      deviceRow = data;
    } else {
      //new device
      const { data, error } = await adminClient
        .from("devices")
        .insert({
          device_code,
          owner_id: user.id,
          device_api_key: crypto.randomUUID(),
        })
        .select()
        .single();

      if (error) {
        return new Response(JSON.stringify({ error: error.message }), {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      deviceRow = data;
    }

    return new Response(
      JSON.stringify({
        device_id: deviceRow.id,
        device_api_key: deviceRow.device_api_key,
      }),
      {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      },
    );
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err.message ?? "Unknown error" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      },
    );
  }
});
